add conditional check for .vault_key file

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -75,7 +75,7 @@ function _clear_task {
 }
 
 function _task_done {
-    printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}${TASK}\n"
+    printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}${TASK}${NC}\n"
     _clear_task
 }
 
@@ -114,13 +114,16 @@ pushd "$DOTFILES_DIR" 2>&1 > /dev/null
 _task "Updating Galaxy"
     _cmd "ansible-galaxy install -r requirements.yml"
 
-_task "Running playbook"; _task_done
-ansible-playbook "$DOTFILES_DIR/test.yml" "$@"
-#if [[ -f $VAULT_SECRET ]]; then
-#    ansible-playbook "$DOTFILES_DIR/site.yml" "$@"
-#else
-#    ansible-playbook "$DOTFILES_DIR/main.yml" "$@"
-#fi
+_task "Running playbook";# _task_done
+if [[ -f $VAULT_SECRET ]]; then
+    _task_done
+    ansible-playbook "$DOTFILES_DIR/main.yml" "$@"
+else
+    printf "${OVERWRITE}${LRED} [X]  ${TASK}${LRED}\n"
+    printf "${LRED} [X]  $VAULT_SECRET file is missing${NC}\n"
+    exit 1
+fi
+_task_done
 
 popd 2>&1 > /dev/null
 
